branch/urls.py
from django.conf.urls import patterns, url, include

from branch.views import CreateSuccessDemand

urlpatterns = patterns(
    '',
    url(r'^new/$', 'branch.views.branch_create', name='branch_create'),
    url(r'^b/(?P<branch_id>\d+)/(?P<slug>[-\w\d]+)/$', 'branch.views.branch_home', name='branch_home'),
    url(r'^leave/(?P<branch_id>\d+)/(?P<user_id>\d+)/$', 'branch.views.branch_leave', name='branch_leave'),
    url(r'^ban/(?P<branch_id>\d+)/(?P<user_id>\d+)/$', 'branch.views.branch_ban', name='branch_ban'),
    url(r'^unban/(?P<branch_id>\d+)/(?P<user_id>\d+)/$', 'branch.views.branch_unban', name='branch_unban'),
    url(r'^promote/(?P<branch_id>\d+)/(?P<user_id>\d+)/$', 'branch.views.branch_promote', name='branch_promote'),
    url(r'^demote/(?P<branch_id>\d+)/(?P<user_id>\d+)/$', 'branch.views.branch_demote', name='branch_demote'),
    url(r'^delete/(?P<branch_id>\d+)/$', 'branch.views.branch_delete', name='branch_delete'),
    url(r'^join/$', 'branch.views.branch_join', name='branch_join'),

    url(r'^volunteer/(?P<volunteer_id>\d+)/accept/', 'branch.views.volunteer_accept', name='volunteer_accept'),
    url(r'^volunteer/(?P<volunteer_id>\d+)/decline/', 'branch.views.volunteer_decline', name='volunteer_decline'),

    # success form
    url(r'^volunteer/success/create/(?P<demand_id>\d+)/$',
         CreateSuccessDemand.as_view(),
         name='success_demand'),
    url(r'^volunteer/unsuccess/(?P<demand_id>\d+)/$',
         'branch.views.unsuccess_job',
         name='unsuccess_job'),
    url(r'^success/manage/(?P<success_demand_id>\d+)/$',
         'branch.views.manage_success',
         name='manage_success'),

    url(r'^b/(?P<branch_id>\d+)/(?P<slug>[-\w\d]+)/jobs/', include('branch.urls_job')),

)

care4care/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

from ajax_select import urls as ajax_select_urls

urlpatterns = patterns(
	'',
    # Examples:
    # url(r'^$', 'care4care.views.home', name='home'),
    url(r'', include('main.urls')),
    (r'^lookups/', include(ajax_select_urls)),
    url(r'^branch/', include('branch.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^translate/', include('rosetta.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf.urls import patterns, url, include

urlpatterns = patterns(
    '',
    url(r'^$', 'main.views.home', name='home'),
    url(r'^social/', include('allauth.urls')),
    url(r'^accounts/logout/$', 'main.views.logout', name='logout'),
    url(r'^accounts/login/$', 'main.views.login', name='login'),
    url(r'^help/$', 'main.views.help', name='help'),
    url(r'^jobs/$', 'main.views.jobs_care4care', name='jobs_care4care'),
    url(r'^about_us/$', 'main.views.about_us', name='about_us'),
    url(r'^what_is/$', 'main.views.what_is', name='what_is'),
    url(r'^agreements/$', 'main.views.agreements', name='agreements'),


    url(r'^accounts/', include('main.urls_register')),
    url(r'^accounts/', include('main.urls_profile')),
    url(r'^accounts/', include('main.urls_verified')),
    url(r'^accounts/', include('main.urls_credits')),

    url(r'^statistics/', include('main.urls_statistics')),
    url(r'^messages/', include('main.urls_postman')),
    url(r'^seek_jobs/', include('main.urls_seek_jobs')),
    url(r'^search/', include('main.urls_search')),
)

branch/models.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.query import QuerySet
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from model_utils.managers import PassThroughManager
from multiselectfield import MultiSelectField

from main.models import User, JobCategory, MemberType

TIME_CHOICES = (
    (1, _('Début de matinée (8h-10h)')),
    (2, _('Fin de matinée (10h-12h)')),
    (3, _('Midi (12h-13h)')),
    (4, _('Début d\'après-midi (13h-16h)')),
    (5, _('Fin d\'après-midi (16h-19h)')),
    (6, _('Repas du soir (19h-20h)')),
    (7, _('Début de soirée (20h-22h)')),
    (8, _('Fin de soirée (22h-00h)')),
    (9, _('Nuit (00h-8h)')),
    )

SHORT_TIME = (
    _('8h-10h'),
    _('10h-12h'),
    _('12h-13h'),
    _('13h-16h'),
    _('16h-19h'),
    _('19h-20h'),
    _('20h-22h'),
    _('22h-00h'),
    _('00h-8h'),
    )

class Branch(models.Model):
    """ Representation of a branch """
    name = models.CharField(verbose_name=_("Nom de la branche"), max_length=255)
    slug = models.SlugField()
    creator = models.ForeignKey(User, verbose_name=_("Créateur de la branche"))
    location = models.CharField(_('Adresse'), max_length=256, null=True, blank=True)
    latitude = models.CharField(_('Latitude'), max_length=20, null=True, blank=True)
    longitude = models.CharField(_('Longitude'), max_length=20, null=True, blank=True)
    members = models.ManyToManyField(User, null=True, blank=True, through='BranchMembers', related_name="members", verbose_name=_("Membres de la branche"))
    banned = models.ManyToManyField(User, null=True, blank=True, related_name="banned_users", verbose_name=_("Membres bannis"))

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Branch, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ('branch_home', (), {'slug' : self.slug, 'branch_id' : self.id})

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

class BranchMembers(models.Model):
    """ Class used for the representation of a member who is in a branch """
    user = models.ForeignKey(User, related_name='membership')
    branch = models.ForeignKey(Branch, related_name='membership')
    is_admin = models.BooleanField(default=False)
    joined = models.DateTimeField(verbose_name=_("date d'arrivé"))

    def __str__(self):
        res = '{} in {}'.format(self.user, self.branch)
        if self.is_admin:
            res += ' [admin]'
        return res

    class Meta:
        ordering = ['-is_admin']

class Comment(models.Model):
    """ Representation of a comment """
    user = models.ForeignKey(User)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    comment = models.TextField(verbose_name=_("Commentez"))
    date = models.DateTimeField(verbose_name=_("Date"), auto_now=True)

    def __str__(self):
        return '{} {} {}'.format(self.user, self.date, self.content_object)

    class Meta:
        ordering = ['date']

class JobManager(QuerySet):
    def up_to_date(self):
        date_now = timezone.now() + timezone.timedelta(hours=-24)
        return self.filter(date__gte=date_now)

    def down_to_date(self):
        date_now = timezone.now() + timezone.timedelta(hours=24)
        return self.filter(date__lte=date_now)

    def no_successs(self):
        return self.filter(success_fill=False)


class Job(models.Model):
    """ Representation of a job (demand or offer) """
    branch = models.ForeignKey(Branch, verbose_name=_("Branche"), related_name="%(class)s_branch")
    donor = models.ForeignKey(User, verbose_name=_("Donneur"), related_name="%(class)s_donor", null=True, blank=True)
    receiver =  models.ForeignKey(User, verbose_name=_("Receveur"), related_name="%(class)s_receiver", null=True, blank=True)
    description = models.TextField(verbose_name=_("Description"), blank=True, null=True)
    category = MultiSelectField(choices=JobCategory.JOB_CATEGORIES, verbose_name=_("Type d'aide"))
    receive_help_from_who = models.IntegerField(choices=MemberType.MEMBER_TYPES_GROUP, default=MemberType.ALL,
                                      verbose_name=_("Qui peut voir et répondre à la demande/offre ?"))
    date = models.DateTimeField(verbose_name=_("Date"))
    time = MultiSelectField(choices=TIME_CHOICES, verbose_name=_("Heures de disponibilité"), blank=False, help_text=_('Selectionnez les heures qui vous conviennent'))

    def get_verbose_category(self):
        if not self.category:
            return ''
        return ', '.join([str(l[1]) for l in JobCategory.JOB_CATEGORIES if (str(l[0]) in self.category)])

    def get_verbose_time(self):
        if not self.time:
            return ''
        return ', '.join([str(l[1]) for l in TIME_CHOICES if (str(l[0]) in self.time)])

    def get_short_time(self):
        if not self.time:
            return ''
        return ', '.join([str(SHORT_TIME[l[0]-1]) for l in TIME_CHOICES if (str(l[0]) in self.time)])

    objects = PassThroughManager.for_queryset_class(JobManager)()

    class Meta:
        abstract = True

class Demand(Job):
    """ Representation of a demand """
    title = models.CharField(_('Titre'), max_length=120, null=True, blank=False)
    location = models.CharField(_('Adresse'), max_length=256, null=True, blank=True)
    latitude = models.CharField(_('Latitude'), max_length=20, null=True, blank=True)
    longitude = models.CharField(_('Longitude'), max_length=20, null=True, blank=True)
    estimated_time = models.IntegerField(verbose_name=_("Temps estimé (en minutes)"), blank=True, null=True)
    real_time = models.IntegerField(verbose_name=_("Temps réel (en minutes)"), blank=True, null=True)
    comments = GenericRelation(Comment)
    volunteers = models.ManyToManyField(User, null=True, blank=True, through='DemandProposition', related_name="volunteers", verbose_name=_("Propositions"))
    closed = models.BooleanField(verbose_name=_("Vontaire assigné"), default=False)
    success_fill = models.BooleanField(verbose_name=_("Demande de confirmation envoyée"), default=False)
    km = models.IntegerField(verbose_name=_("Distance depuis domicile"), blank=True, null=True)
    success = models.NullBooleanField(verbose_name=_("Tâche finie avec succès"), null=True, blank=True, default=None)

    @models.permalink
    def get_absolute_url(self):
        return ('see_demand', (), {'branch_id': self.branch.id, 'slug': self.branch.slug, 'demand_id': self.id})

    def __str__(self):
        return '{} - {} - {}'.format(self.title, self.receiver, self.branch)

    class Meta:
        ordering = ['date']

class Offer(Job):
    """ Representation of a job """
    comments = GenericRelation(Comment)

    @models.permalink
    def get_absolute_url(self):
        return ('see_offer', (), {'branch_id': self.branch.id, 'slug': self.branch.slug, 'offer_id': self.id})
    def __str__(self):
        return '{} - {}'.format(self.donor, self.branch)

    class Meta:
        ordering = ['date']

class DemandPropositionManager(QuerySet):
    def up_to_date(self):
        date_now = timezone.now() + timezone.timedelta(hours=-24)
        return self.filter(demand__date__gte=date_now)

    def down_to_date(self):
        date_now = timezone.now() + timezone.timedelta(hours=24)
        return self.filter(demand__date__lte=date_now)

    def no_successs(self):
        return self.filter(demand__success_fill=False)

class DemandProposition(models.Model):
    """ Representation of a demand Proposition"""
    user = models.ForeignKey(User, related_name='uservol')
    demand = models.ForeignKey(Demand, related_name='propositions')
    comment = models.TextField(verbose_name=_("Commentaire (facultatif)"), blank=True, null=True)
    created = models.DateTimeField(verbose_name=_("Date de création"), auto_now=True)
    accepted = models.BooleanField(verbose_name=_("Proposition acceptée"), default=False)
    km = models.IntegerField(verbose_name=_("Distance depuis domicile"), blank=True, null=True)
    time = MultiSelectField(choices=TIME_CHOICES, verbose_name=_("Heure(s) choisie(s)"), blank=False, help_text=_('Selectionnez les heures qui vous conviennent'))

    objects = PassThroughManager.for_queryset_class(DemandPropositionManager)()

    def get_verbose_time(self):
        if not self.time:
            return ''
        return ', '.join([str(l[1]) for l in TIME_CHOICES if (str(l[0]) in self.time)])

    class Meta:
        ordering = ['-created']


class SuccessDemand(models.Model):
    """ Representation of a complete demand"""
    demand = models.ForeignKey(Demand, related_name='success_demand', blank=True, null=True)
    comment = models.TextField(verbose_name=_('Commentaire'), blank=True, null=True)
    time = models.IntegerField(verbose_name=_("Temps passé (en minutes)"), blank=True, null=True)
    ask_to = models.ForeignKey(User, related_name='success_pending', blank=True, null=True)
    asked_by = models.ForeignKey(User, related_name='approval_pending', blank=True, null=True)
    branch = models.ForeignKey(Branch, related_name='success_branch_pending', blank=True, null=True)
    created = models.DateTimeField(verbose_name=_("Date de création"), auto_now=True)

    class Meta:
        ordering = ['-created']

branch/templates/job/manage_success.html
{% extends "base.html" %}
{% load bootstrap3 %}{% load i18n %}{% load staticfiles %}


{% block title %}{% trans "Aider" %}{% endblock %}


{% block content %}


<div class="row mt">
    <div class="col-lg-12 ph">
        <form action="." class="form-horizontal style-form" role="form" method="post">
            {% csrf_token %}

            {% bootstrap_form_errors form %}

            <div class="col-lg-12 col-sm-12 background-gris">
                <div class="showback">

                    {% blocktrans with demand.donor as donor and demand.title as title %}
                    <h3 class="mb"> Confirmer que {{ donor }} a bien effectué votre tâche "{{ title }}"</h3>
                    {% endblocktrans %}

                    {% blocktrans with demand.donor.get_full_name as donor and success.time as time and demand.title as title %}
                    <p>
                      {{ donor }} déclare vous avoir aidé pendant {{ time }} minutes pour votre demande "{{ title }}".
                      <br />
                      Si ces informations sont correctes, vous serez débité de {{ time }} minutes de crédit-temps.
                      <br />
                      Vous pouvez laisser un petit message en commentaire si vous le souhaitez.
                    </p>
                    {% endblocktrans %}

                    {% bootstrap_form form %}
                </div>
            </div>

            <div class="col-sm-12">
            {% buttons %}
            <div class="row">
                <div class="col-md-6 mb"><button type="submit" name="accept" class="btn btn-success btn-lg btn-block">
                    {% bootstrap_icon "ok" %} &nbsp; {% trans "Confirmer" %}
                </button></div>
                <div class="col-md-6 mb"><button type="submit" name="decline" class="btn btn-primary btn-lg btn-block">
                    {% bootstrap_icon "remove" %} &nbsp; {% trans "Refuser" %}
                </button></div>
            </div>
            {% endbuttons %}
            </div>
        </form>
    </div>
</div>

{% endblock %}


{% block extra_footer %}

{% endblock %}

branch/templates/job/need_help.html
{% extends "base.html" %}
{% load bootstrap3 %}{% load i18n %}{% load staticfiles %}


{% block title %}{% trans "Besoin d'aide" %}{% endblock %}

{% block extra_head %}
<script src="{% static "js/bloodhound.min.js" %}"></script>
<script src="http://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
<script src="{% static "js/typeahead-addresspicker.js" %}"></script>
<script src="{% static "js/typeahead.js" %}"></script>

{% endblock %}

{% block content %}

<h3> {% trans "Demande d'aide de" %} {{ ruser.get_full_name }} {% trans "dans la branche"%} {{ branch }}</h3>

<div class="row mt">
    <div class="col-lg-12">
        <form action="." class="form-horizontal style-form" role="form" method="post">
            {% csrf_token %}

            {% bootstrap_form_errors form %}

            <div class="col-lg-12 col-sm-12 background-gris">
                <div class="showback">
                    <h4 class="mb"> {% trans "Informations générales" %}</h4>
                    {% bootstrap_field form.title %}
                    {% if not update %}
                    {% bootstrap_field form.category %}
                    {% endif %}

                    {% bootstrap_field form.date %}
                    {% bootstrap_field form.time %}

                    {% bootstrap_field form.estimated_time %}
                    {% bootstrap_field form.receive_help_from_who %}
                    {% bootstrap_field form.description %}
                </div>
            </div>

            <div class="col-sm-12 background-gris">
              <div class="showback">
              <h4 class="mb">{% trans "Adresse" %}</h4>
              <div class="row">
                <div class="col-lg-6">
                  <input id="id_location_input" class="typeahead form-control" type="text" placeholder="{% trans "Entrez votre adresse"%}" value="{% if form.location.value %}{{ form.location.value }}{% else %}{% if ruser.location %}{{ ruser.location }}{% endif %}{% endif %}">
                  <div class="alert alert-danger mt"><b>{% trans "Information:"%}</b> {% trans "Si vous ne souhaitez pas révéler entièrement votre adresse, n'indiquez que la rue ou un endroit proche. Vous pourrez préciser ensuite votre adresse exacte à la personne qui se proposera afin de vous aider dans votre tâche." %}</div>
                </div>
                <div class="col-lg-6">
                  <div id="map" style="min-height:300px;"></div>
                  <br />
                  <div class="alert alert-info"><b>{% trans "Information:"%}</b> {% trans "L'emplacement sur la carte peut être approximatif" %}</div>
                </div>
              </div>
              {% bootstrap_field form.location %}
              {% bootstrap_field form.latitude %}
              {% bootstrap_field form.longitude %}
              </div>
            </div>

            <div class="col-sm-12">
            {% buttons %}
            <div class="row">
                <div class="col-md-6 mb"><button type="submit" class="btn btn-success btn-lg btn-block">
                        {% bootstrap_icon "ok" %} &nbsp; {% trans "Envoyer" %}
                </button></div>
                <div class="col-md-6"><a href="{% url 'home' %}" class="btn btn-danger btn-lg btn-block">
                        {% bootstrap_icon "remove" %} &nbsp; {% trans "Annuler" %}
                </a></div>
            </div>
            {% endbuttons %}
            </div>

        </form>
    </div>
</div>

{% endblock %}


{% block extra_footer %}
<script>
$(document).ready(function () {
// https://github.com/sgruhier/typeahead-addresspicker
// instantiate the addressPicker suggestion engine (based on bloodhound)
var addressPicker = new AddressPicker({
  map: {id: '#map', center: new google.maps.LatLng({% if form.latitude.value %}'{{ form.latitude.value }}'{% else %}{% if ruser.latitude %}'{{ruser.latitude}}'{% else %}'50.846975'{% endif %}{% endif %}, {% if form.longitude.value %}'{{ form.longitude.value }}'{% else %}{% if ruser.longitude %}'{{ruser.longitude}}'{% else %}'4.351815699999975'{% endif %}{% endif %}), zoom:15, scrollwheel: false},
  marker: {visible: true, draggable: false,}
});

// instantiate the typeahead UI
$('#id_location_input').typeahead(null, {
  displayKey: 'description',
  source: addressPicker.ttAdapter()
});

// Bind some event to update map on autocomplete selection
$('#id_location_input').bind("typeahead:selected", addressPicker.updateMap);
$('#id_location_input').bind("typeahead:cursorchanged", addressPicker.updateMap);

addressPicker.bindDefaultTypeaheadEvent($('#id_location_input'))

$(addressPicker).on('addresspicker:selected', function (event, result) {
  $('#id_latitude').val(result.lat());
  $('#id_longitude').val(result.lng());
  $('#id_location').val($('#id_location_input').typeahead('val'));
});

});
</script>
{{ form.media }}
{% endblock %}

branch/templates/job/offer_help.html
{% extends "base.html" %}
{% load bootstrap3 %}{% load i18n %}{% load staticfiles %}


{% block title %}{% trans "Offrir de l'aide" %}{% endblock %}

{% block extra_head %}
<script src="{% static "js/bloodhound.min.js" %}"></script>
<script src="http://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
<script src="{% static "js/typeahead-addresspicker.js" %}"></script>
<script src="{% static "js/typeahead.js" %}"></script>

{% endblock %}

{% block content %}

<h3>{{ ruser.get_full_name }} {% trans "offre de l'aide dans la branche"%} {{ branch }}</h3>

<div class="row mt">
    <div class="col-lg-12">
        <form action="." class="form-horizontal style-form" role="form" method="post">
            {% csrf_token %}

            <div class="col-lg-12 col-sm-12 background-gris">
                <div class="showback">
                    <h4 class="mb"> {% trans "Informations générales" %}</h4>
                    {% bootstrap_form form %}
                </div>
            </div>


            <div class="col-sm-12">
            {% buttons %}
            <div class="row">
                <div class="col-md-6 mb"><button type="submit" class="btn btn-success btn-lg btn-block">
                        {% bootstrap_icon "ok" %} &nbsp; {% trans "Envoyer" %}
                </button></div>
                <div class="col-md-6"><a href="{% url 'home' %}" class="btn btn-danger btn-lg btn-block">
                        {% bootstrap_icon "remove" %} &nbsp; {% trans "Annuler" %}
                </a></div>
            </div>
            {% endbuttons %}
            </div>

        </form>
    </div>
</div>

{% endblock %}


{% block extra_footer %}
{{ form.media }}
{% endblock %}

branch/templates/job/take_offer.html
{% extends "base.html" %}
{% load bootstrap3 %}{% load i18n %}{% load staticfiles %}


{% block title %}{% trans "Besoin d'aide" %}{% endblock %}

{% block extra_head %}
<script src="{% static "js/bloodhound.min.js" %}"></script>
<script src="http://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
<script src="{% static "js/typeahead-addresspicker.js" %}"></script>
<script src="{% static "js/typeahead.js" %}"></script>

{% endblock %}

{% block content %}

<h3> {% trans "Demande d'aide de " %}{{ ruser.get_full_name }}{% trans " dans la branche "%}{{ branch }} - {{ offer.date|date:"DATE_FORMAT"}}</h3>

<div class="alert alert-info" role="alert">
  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
  <span class="sr-only">{% trans "Information" %}</span>
  {% blocktrans with offer.donor.get_full_name as name %}
  Afin de profiter de l'offre de {{name}}, vous devez remplir une demande rentrant dans ses critères.<br />
  Ce formulaire vous limite donc afin que l'utilisateur {{name}} soit intéressé par votre demande.<br />
  Cet utilisateur sera ensuite averti et pourra décider de vous venir en aide.
  {% endblocktrans %}
</div>

<div class="row mt">
    <div class="col-lg-12">
        <form action="." class="form-horizontal style-form" role="form" method="post">
            {% csrf_token %}

            {% bootstrap_form_errors form %}

            <div class="col-lg-12 col-sm-12 background-gris">
                <div class="showback">
                    <h4 class="mb"> {% trans "Informations générales" %}</h4>
                    {% bootstrap_field form.title %}
                    {% if not update %}
                    {% bootstrap_field form.category %}
                    {% endif %}

                    {% bootstrap_field form.time %}

                    {% bootstrap_field form.estimated_time %}
                    {% bootstrap_field form.receive_help_from_who %}
                    {% bootstrap_field form.description %}
                </div>
            </div>

            <div class="col-sm-12 background-gris">
              <div class="showback">
              <h4 class="mb">{% trans "Adresse" %}</h4>
              <div class="row">
                <div class="col-lg-6">
                  <input id="id_location_input" class="typeahead form-control" type="text" placeholder="{% trans "Entrez votre adresse"%}" value="{% if form.location.value %}{{ form.location.value }}{% else %}{% if ruser.location %}{{ ruser.location }}{% endif %}{% endif %}">
                  <div class="alert alert-danger mt"><b>{% trans "Information:"%}</b> {% trans "Si vous ne souhaitez pas révéler entièrement votre adresse, n'indiquez que la rue ou un endroit proche. Vous pourrez préciser ensuite votre adresse exacte à la personne qui se proposera afin de vous aider dans votre tâche." %}</div>
                </div>
                <div class="col-lg-6">
                  <div id="map" style="min-height:300px;"></div>
                  <br />
                  <div class="alert alert-info"><b>{% trans "Information:"%}</b> {% trans "L'emplacement sur la carte peut être approximatif" %}</div>
                </div>
              </div>
              {% bootstrap_field form.location %}
              {% bootstrap_field form.latitude %}
              {% bootstrap_field form.longitude %}
              </div>
            </div>

            <div class="col-sm-12">
            {% buttons %}
            <div class="row">
                <div class="col-md-6 mb"><button type="submit" class="btn btn-success btn-lg btn-block">
                        {% bootstrap_icon "ok" %} &nbsp; {% trans "Envoyer" %}
                </button></div>
                <div class="col-md-6"><a href="{% url 'home' %}" class="btn btn-danger btn-lg btn-block">
                        {% bootstrap_icon "remove" %} &nbsp; {% trans "Annuler" %}
                </a></div>
            </div>
            {% endbuttons %}
            </div>

        </form>
    </div>
</div>

{% endblock %}


{% block extra_footer %}
<script>
$(document).ready(function () {

  // to_keep_time
  var to_keep_time = [
  {% for pt in offer.time %}
    {{pt}}-1,
  {% endfor %}
  ]
  var total_checkbox = $("div.checkbox").length;
  for(var i=0; i < total_checkbox; ++i){

    if(to_keep_time.indexOf(i) !== -1){
      
    } else {
      $('#id_time_'+i+'').parent().parent().remove();
    }
  }

  // to_keep_category

  function da_int(p){
    p = parseInt(p);
    if(p === 'a'){
      return '10';
    }
  }

  var to_keep_category = [
  {% for pt in category_keep %}
    {{pt}} - 1,
  {% endfor %}
  ]

  var total_radio = $("div.radio").length;
  for(var i=0; i < total_radio; ++i){

    if(to_keep_category.indexOf(i) !== -1){
      
    } else {
      $('#id_category_'+i+'').parent().parent().remove();
    }
  }

// https://github.com/sgruhier/typeahead-addresspicker
// instantiate the addressPicker suggestion engine (based on bloodhound)
var addressPicker = new AddressPicker({
  map: {id: '#map', center: new google.maps.LatLng({% if form.latitude.value %}'{{ form.latitude.value }}'{% else %}{% if ruser.latitude %}'{{ruser.latitude}}'{% else %}'50.846975'{% endif %}{% endif %}, {% if form.longitude.value %}'{{ form.longitude.value }}'{% else %}{% if ruser.longitude %}'{{ruser.longitude}}'{% else %}'4.351815699999975'{% endif %}{% endif %}), zoom:15, scrollwheel: false},
  marker: {visible: true, draggable: false,}
});

// instantiate the typeahead UI
$('#id_location_input').typeahead(null, {
  displayKey: 'description',
  source: addressPicker.ttAdapter()
});

// Bind some event to update map on autocomplete selection
$('#id_location_input').bind("typeahead:selected", addressPicker.updateMap);
$('#id_location_input').bind("typeahead:cursorchanged", addressPicker.updateMap);

addressPicker.bindDefaultTypeaheadEvent($('#id_location_input'))

$(addressPicker).on('addresspicker:selected', function (event, result) {
  $('#id_latitude').val(result.lat());
  $('#id_longitude').val(result.lng());
  $('#id_location').val($('#id_location_input').typeahead('val'));
});

});
</script>
{{ form.media }}
{% endblock %}